### ISSUE TITLE
Deleting a `DatabaseUser` results into a validation failed on password

### ISSUE THREAD

**Issue by mbardelmeijer** [CyberfusionNL/cyberfusion-cluster-api-client#37]
## Goal

I'm trying to delete a database user object. I'm getting the following exception when trying to delete it. It seems that the `null` factor for the database user password field isn't handled correctly.

## Additional information

```
Cyberfusion\ClusterApi\Exceptions\ValidationException: The validation failed: `length_max: 255 failed on NULL, pattern: ^[ -~]+$ failed on NULL` in vendor/cyberfusion/cluster-api-client/src/Exceptions/ValidationException.php:11

#0 /vendor/cyberfusion/cluster-api-client/src/Support/Validator.php(210): Cyberfusion\ClusterApi\Exceptions\ValidationException::validationFailed()
#1 /vendor/cyberfusion/cluster-api-client/src/Models/DatabaseUser.php(68): Cyberfusion\ClusterApi\Support\Validator->validate()
#2 /vendor/cyberfusion/cluster-api-client/src/Models/DatabaseUser.php(143): Cyberfusion\ClusterApi\Models\DatabaseUser->setPassword()
#3 /vendor/cyberfusion/cluster-api-client/src/Endpoints/DatabaseUsers.php(64): Cyberfusion\ClusterApi\Models\DatabaseUser->fromArray()
#4 /vendor/cyberfusion/cluster-api-client/src/Endpoints/DatabaseUsers.php(166): Cyberfusion\ClusterApi\Endpoints\DatabaseUsers->get()

```

**Comment by dvdheiden** [comment]
Thank you for reporting this issue. I really need to make some time to solve: https://github.com/CyberfusionNL/cyberfusion-cluster-api-client/issues/7 but will fix this ASAP.
